import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai';
import Image from 'next/image';
import keelan from '../public/keelan.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Portofolio Eh!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">developedbypixelshot</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-gray-900 dark:text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Pixelshot
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-sky-200">
              Freelance providing services for programming needs. Join me down
              below and let&apos;s get acquainted!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={keelan} layout="fill" objectFit="cover" alt="" />
          </div>
        </section>
        {/* <!--- Second section/page ---> */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-sky-200">
              Since the beginning of my journey as a freelance developer,
              I&apos;ve done remote work for{' '}
              <span className="text-teal-500"> agencies </span> consulted for{' '}
              <span className="text-teal-500">startups</span> and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-sky-200">
              I offer from a wide range of services, including programming and
              teaching.
            </p>
          </div>
          {/* <!--- Card section ---> */}
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg shadow-gray-300/80 p-10 rounded-xl my-10 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 duration-300">
              <Image src={design} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2">Card 1</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 dark:text-fuchsia-200 py-1 hover:text-gray-800">
                Photoshop
              </p>
              <p className="text-gray-800 dark:text-fuchsia-200 py-1 hover:text-gray-800">
                Illustrator
              </p>
              <p className="text-gray-800 dark:text-fuchsia-200 py-1 hover:text-gray-800">
                Figma
              </p>
            </div>
            <div className="text-center shadow-lg shadow-gray-300/80 p-10 rounded-xl my-10 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 duration-300">
              <Image src={code} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2">Card 2</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 dark:text-rose-200 py-1">Photoshop</p>
              <p className="text-gray-800 dark:text-rose-200 py-1">
                Illustrator
              </p>
              <p className="text-gray-800 dark:text-rose-200 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg shadow-gray-300/80 p-10 rounded-xl my-10 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 duration-300">
              <Image src={consulting} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2">Card 3</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 dark:text-amber-200 py-1">
                Photoshop
              </p>
              <p className="text-gray-800 dark:text-amber-200 py-1">
                Illustrator
              </p>
              <p className="text-gray-800 dark:text-amber-200 py-1">Figma</p>
            </div>
          </div>
        </section>
        {/* <!--- Portofolio section ---> */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-sky-200">
              Since the beginning of my journey as a freelance developer,
              I&apos;ve done remote work for{' '}
              <span className="text-teal-500"> agencies </span> consulted for{' '}
              <span className="text-teal-500">startups</span> and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-sky-200">
              I offer from a wide range of services, including programming and
              teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt=""
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 duration-300"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt=""
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 duration-300"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt=""
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 duration-300"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                alt=""
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 duration-300"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                alt=""
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 duration-300"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                alt=""
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 duration-300"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
